[package]
name = "task"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
chrono = { workspace = true }
shellexpand = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
