[package]
name = "organon"
version = "0.0.0"
edition = "2021"
authors = ["Jason Lenoble <jason.lenoble@gmail.com>"]
repository = "https://github.com/jlenoble/organon-rust"

[dev-dependencies]
"tempfile" = "3.3.0"
