[package]
name = "tw"
version = "0.0.0"
edition = "2021"
description = "a port of taskwarrior from C++"
publish = false

[dependencies]
permissions = { workspace = true }
shellexpand = { workspace = true }
