[package]
name = "impl_extract_for_syn"
version = "0.0.0"
edition = "2021"

[dependencies]
# Procedural macros
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
